CREATE DATABASE IF NOT EXISTS MUEBLERIA;
USE MUEBLERIA;


CREATE TABLE IF NOT EXISTS MATERIA_PRIMA (
	tipo VARCHAR(40),
	costo DECIMAL(5, 2) UNSIGNED,
	cantidad INT UNSIGNED NOT NULL,
    CONSTRAINT PK_MATERIA_PRIMA PRIMARY KEY (tipo, costo)
);

CREATE TABLE IF NOT EXISTS MUEBLE (
	nombre VARCHAR(40),
	precio DECIMAL(6, 2) UNSIGNED NOT NULL,
    CONSTRAINT PK_MUEBLE PRIMARY KEY (nombre)
);

CREATE TABLE IF NOT EXISTS USUARIO (
	nombre_usuario VARCHAR(40),
    contraseña VARCHAR(40) NOT NULL,
    tipo DECIMAL(1, 0) UNSIGNED NOT NULL,
	activo BOOLEAN NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (nombre_usuario)
);

CREATE TABLE IF NOT EXISTS CLIENTE (
	nit CHAR(6),
    nombre VARCHAR(40),
    direccion VARCHAR(40) NOT NULL,
    municipio VARCHAR(25),
    departamento VARCHAR(25),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (nit)
);

CREATE TABLE IF NOT EXISTS FACTURA (
	num_factura INT(13) UNSIGNED AUTO_INCREMENT,
    cliente CHAR(6) NOT NULL,
    fecha_compra DATE NOT NULL,
    CONSTRAINT PK_FACTURA PRIMARY KEY (num_factura),
    CONSTRAINT FK_FACTURA_CLIENTE
		FOREIGN KEY (cliente) REFERENCES CLIENTE (nit)
);

CREATE TABLE IF NOT EXISTS INDICACIONES (
	mueble VARCHAR(40),
	tipo_pieza VARCHAR(40),
	costo_pieza DECIMAL(5, 2) UNSIGNED,
	cantidad INT UNSIGNED NOT NULL,
    CONSTRAINT PK_INDICACIONES PRIMARY KEY (mueble, tipo_pieza, costo_pieza),
    CONSTRAINT FK_INDICACIONES_MUEBLE
		FOREIGN KEY (mueble) REFERENCES MUEBLE (nombre),
    CONSTRAINT FK_INDICACIONES_MATERIA_PRIMA
		FOREIGN KEY (tipo_pieza, costo_pieza)
            REFERENCES MATERIA_PRIMA (tipo, costo)
            ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ENSAMBLADO (
	mueble_id INT(4) UNSIGNED AUTO_INCREMENT,
    fecha_ensamble DATE NOT NULL,
    ensamblador VARCHAR(40) NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    coste DECIMAL(6, 2) UNSIGNED NOT NULL,
    CONSTRAINT Pk_ENSAMBLADO PRIMARY KEY (mueble_id),
    CONSTRAINT FK_ENSAMBLADO_USUARIO
		FOREIGN KEY (ensamblador) REFERENCES USUARIO (nombre_usuario),
	CONSTRAINT FK_ENSAMBLADO_MUEBLE
		FOREIGN KEY (tipo) REFERENCES MUEBLE (nombre)
);

CREATE TABLE IF NOT EXISTS FACTURADO (
	factura INT(13) UNSIGNED,
    num_compra TINYINT UNSIGNED,
    mueble INT(4) UNSIGNED,
    precio DECIMAL(6, 2) UNSIGNED NOT NULL,
    devuelto BOOLEAN NOT NULL,
    CONSTRAINT PK_FACTURADO PRIMARY KEY (factura, num_compra),
	CONSTRAINT FK_FACTURADO_FACTURA
		FOREIGN KEY (factura) REFERENCES FACTURA (num_factura),
    CONSTRAINT FK_FACTURADO_MUEBLE
		FOREIGN KEY (mueble) REFERENCES ENSAMBLADO (mueble_id)
);